from models.question import Question
from models.course_material import CourseMaterial

"""
This class generates new exam questions by querying an LLM.
"""
class QuestionGenerator:

    PROMPT = "" # write your prompt here
    
    # buiild your constructor here
    def __init__(self):
        pass

    """
    Queries the LLM using a prompt enriched with relevant course material and old exam questions.
    
    Input:
        course_id... The ID of the course the exam questions should be generated for
        relevant_course_material... Relevant course material along with some metadata, queried from our vector DB
        old_questions... Old exam questions along with some metadata, queried from our vector DB
        n_new_questions... How many questions should be generated by the LLM
    Output:
        list[Question]... A list of `n_new_questions` newly generated exam questions
    """
    def generate_questions(
        self, 
        course_id: int, 
        relevant_course_material: list[CourseMaterial], 
        old_questions: list[Question],
        n_new_questions: int = 20
    ) -> list[Question]:
        pass