from models.question_type import QuestionType
from dataclasses import dataclass

"""
This class represents a question that is either generated by an LLM or given to the LLM to generate a new exam.
"""
@dataclass
class Question:
    question: str # The text of the question
    question_type: QuestionType
    answer_keys: list[str] | None = None # empty for QuestionType.TEXT_ANSWER, else the multiple choice answers are here
    metadata: dict # the metadata of this question e.g. 'topic', etc.